# Generated by Django 5.2.1 on 2025-05-16 12:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('discount_price', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('image', models.ImageField(upload_to='stores')),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='stores')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='stores')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='stores')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='stores')),
                ('photo5', models.ImageField(blank=True, null=True, upload_to='stores')),
                ('is_available', models.BooleanField(default=True)),
                ('in_stock', models.IntegerField()),
                ('product_id', models.UUIDField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stores.category')),
            ],
        ),
    ]
